### ISSUE TITLE
No componentDidUnmount lifecycle method

### ISSUE THREAD

**Issue by phated** [AmpersandJS/ampersand-react-mixin#2]
React only has the lifecycle method `componentWillUnmount` and not `componentDidUnmount` because they want you to unbind all handlers before they remove the component from the DOM.

**Comment by lukekarrys** [comment]
Thanks @phated!

**Comment by kshivakumar** [comment]
Another logical explanation
> Once the component is unmounted, the instance no longer exists. If the instance continued to execute instructions, it'd be equivalent of someone operating from the grave. 

source: http://buildwithreact.com/article/component-lifecycle
